# Generated by Django 3.1.7 on 2021-03-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('landing_url', models.CharField(max_length=200)),
            ],
        ),
    ]
